### ISSUE TITLE
please increase Block size in pixels limit to 25 or even more

### ISSUE THREAD

**Issue by kakini** [catholicon/OfflineQR#17]
reason: I am using a hi res monitor and also want to be able read 
the QR code from some distance.

Many thanks for this really nice add-on!
-k

**Comment by catholicon** [comment]
@kakini, aren't zoom buttons working for you? (Admittedly, to unclutter UI, those button show up when you hover over the code... your zoom setting would be persisted though)

**Comment by kakini** [comment]
Yes, the zoom buttons work just fine, I just would still want to have bigger QR  size because it is too small for my hardware QR scanner - it works better if QR code is big enough.

**Comment by catholicon** [comment]
@kakini, if you're comfortable editing code, then you can edit this line (https://github.com/catholicon/OfflineQR/blob/master/lib/main.js#L260) to have a bigger upper limit. Using 10 was completely arbitrary on my part -- do you think some other number suits better?

**Comment by kakini** [comment]
thats not all, you also have to modify canvas size calculation and a few other places.
I think 25 limit should be fine.
Greetings,
Karl

**Comment by catholicon** [comment]
Ohk... I totally forgot about those :). Assigning it to myself -- and patches welcome ;)

**Comment by kakini** [comment]
On Tue 150512, Vikas Saurabh wrote:
> Ohk... I totally forgot about those :). Assigning it to myself -- and patches welcome ;)
> 

here you are :-) 25 seems to be big enough.

Greetings,
Karl

diff --git a/data/htmlQR/index.html b/data/htmlQR/index.html
index 5bf6e72..15815bf 100644
--- a/data/htmlQR/index.html
+++ b/data/htmlQR/index.html
@@ -111,7 +111,7 @@
 				if(errorCorrectLevel==undefined)errorCorrectLevel = "L";
 			}
 
-			if(isNaN(blockSize) || blockSize<1 || blockSize>10)
+			if(isNaN(blockSize) || blockSize<1 || blockSize>25)
 			{
 				blockSize = undefined;
 			}
@@ -147,7 +147,7 @@
 	
 			var modCount = getModuleCountForVersion(reqVersion);
 			
-			var canvasSize = Math.max(60, Math.min(400, (modCount+8)*blockSize));
+			var canvasSize = Math.max(60, Math.min(768, (modCount+8)*blockSize));
 			
 			var element = document.getElementById("qrcode");
 
@@ -245,7 +245,7 @@
 		}
 		function setZoomLevel(zoomLevel)
 		{
-			if(isNaN(zoomLevel) || zoomLevel<1 || zoomLevel>10)return;
+			if(isNaN(zoomLevel) || zoomLevel<1 || zoomLevel>25)return;
 			
 			if(lastUpdateQRCodeParams)lastUpdateQRCodeParams["blockSize"]=zoomLevel;
 			updateQRCodeWithTA();
@@ -346,4 +346,4 @@
 		</div>
 	</div>
   </body>
-</html>
\ No newline at end of file
+</html>
diff --git a/lib/main.js b/lib/main.js
index 3e94d70..ca0b0af 100644
--- a/lib/main.js
+++ b/lib/main.js
@@ -159,7 +159,8 @@ var qrCodePanel = panel.Panel(
 {
 	width: 30,
 	height: 30,
-	contentURL: data.url("htmlQR/index.html?isAddon=true")
+	contentURL: data.url("htmlQR/index.html?isAddon=true"),
+	contextMenu: true
 });
 qrCodePanel.on("show", function()
 {
@@ -257,9 +258,9 @@ function handlePrefChange(prefName)
 			break;
 		case "QRBlockSize":
 			prefVal = prefs.prefs["QRBlockSize"];
-			if(prefVal<1 || prefVal>10)
+			if(prefVal<1 || prefVal>25)
 			{
-				prefs.prefs["QRBlockSize"] = 3;
+				prefs.prefs["QRBlockSize"] = 10;
 			}
 			break;
 		case "ShowInContextMenu":
@@ -281,7 +282,7 @@ function getPreferredBlockSize()
 
 function setPreferredBlockSize(blockSize)
 {
-	if(isNaN(blockSize) || blockSize<1 || blockSize>10)
+	if(isNaN(blockSize) || blockSize<1 || blockSize>25)
 		return;
 
 	prefs.prefs["QRBlockSize"] = blockSize;
@@ -306,4 +307,4 @@ function setShowExtraUI(showExtraUI)
 {
 	if(showExtraUI!=undefined)
 		prefs.prefs["showExtraUI"] = showExtraUI;
-}
\ No newline at end of file
+}
diff --git a/package.json b/package.json
index 8240af0..e57b317 100644
--- a/package.json
+++ b/package.json
@@ -21,9 +21,9 @@
 		},
 		{
 			"name": "QRBlockSize",
-			"title": "Block size in pixel (1-10)",
+			"title": "Block size in pixel (1-25)",
 			"type": "integer",
-			"value": 3
+			"value": 10
 		}
 	],
 	"permissions": {"private-browsing": true}



> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/catholicon/OfflineQR/issues/17#issuecomment-101237110

-- 
Dipl. Ing. Karl Kiniger    mailto:karl.kiniger@med.ge.com
Tel: (++43) 7682-3800-710  Voip(GE-internal): 1662 710
Fax: (++43) 7682-3800-47   C: +43 6991 3800 710
-
GE Healthcare Austria GmbH & Co OG - Tiefenbach 15 - 4871 Zipf Austria
Landesgericht Wels FN 222387s - UID (VAT-ID): ATU54086108 - DVR: 2111103 - ARA: 12816
Persönlich haftende Gesellschafterin: GE Jenbacher GmbH
Donaucitystraße 6/3, 1220 Wien, Österreich - Handelsgericht Wien FN 234609p

**Comment by catholicon** [comment]
Cool!... thanks :)... would upload patched version to AMO by the weekend. BTW, I'd probably not change the default size to 10. I guess that's fine :)

**Comment by kakini** [comment]
On Tue 150512, Vikas Saurabh wrote:
> Cool!... thanks :)... would upload patched version to AMO by the weekend. BTW, I'd probably not change the default size to 10. I guess that's fine :)

It _is_ fine :)

Karl
