### ISSUE TITLE
Menu Wizard: Icon not hideable

### ISSUE THREAD

**Issue by rugk** [catholicon/OfflineQR#20]
With [Menu Wizard](https://addons.mozilla.org/de/firefox/addon/s3menu-wizard/) I cannot hide the context menu entry:
![showqrblocked](https://cloud.githubusercontent.com/assets/11966684/10909870/321ffa0e-823c-11e5-94b0-88f45d0a3464.png)

I know there is an option in the settings to change this, but it is nicer to be able to use your own way to do this if you want.

**Comment by rugk** [comment]
As it is said in [another repo with the same error](https://github.com/brettz9/jump-to-anchor/issues/4) the fix may depend on https://bugzilla.mozilla.org/show_bug.cgi?id=956461, because the Firefox SDK does not allow adding IDs.
Do you use the SDK?

**Comment by catholicon** [comment]
Thanks for reporting the issue @rugk. Yes, I do you Firefox SDK, so it'd very well be the same issue you identified. I'm closing this issue now. I'd get to your other issues a little later though.

**Comment by rugk** [comment]
In Menu Wizard 4.01 the developer of Menu Wizard added a workaround. You can now activate this option in the settings:
![menuwizardsetid](https://cloud.githubusercontent.com/assets/11966684/12376672/b7a68158-bd00-11e5-8400-9bd46846ea38.PNG)

With this option activated you can hide the menu icon again.
