### ISSUE TITLE
"QR for selected text" missing

### ISSUE THREAD

**Issue by ariel-co** [catholicon/OfflineQR#26]
Firefox version 44.0a2 (2015-12-01), currently in Aurora channel

To reproduce: highlight text. Right click / press <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>Q</kbd>.

Expected result: the context menu offers "Show QR for the selected text" / a QR code for the highlighted text is generated.

Actually: the option is missing from the context menu / the shortcut generates a QR code for the current page's URL.

**Comment by catholicon** [comment]
Tried it just now on FF49.0.1 and QR for selection is working fine. The string in context menu is "Show QR" though.
